---

- name: Obtain admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword 
  register: admin_password_file

- name: Install Jenkins plugins from latest versions
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }} --username admin --password {{ admin_password_file.stdout }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins

- name: Install Jenkins plugins from specific versions
  get_url: 
    url: http://updates.jenkins-ci.org/download/plugins/{{ item.key }}/{{ item.value.version }}/{{ item.key }}.{{ item.value.extension }} 
    dest: "{{ jenkins_home }}/plugins/{{ item.key }}.{{ item.value.extension}}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  with_dict: "{{ jenkins_plugin_versions }}"
  notify: restart jenkins

