---
# The playbook for Ant tasks

- name: Download Ant
  command: "wget http://www-eu.apache.org/dist//ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz chdir=/opt/devops/install/ creates=/opt/devops/install/apache-ant-{{ ant_version }}-bin.tar.gz"
  tags: ant

- name: Unarchive the compressed Ant binaries
  unarchive: "copy=no src=/opt/devops/install/apache-ant-{{ ant_version }}-bin.tar.gz dest=/opt/devops/ creates=/opt/devops/apache-ant-{{ ant_version }}"
  tags: ant

- name: Set ANT_HOME environment variable
  lineinfile: dest=/etc/environment regexp='^ANT_HOME.*' line='ANT_HOME=/opt/devops/apache-ant-{{ ant_version }}' insertbefore='^PATH.*'
  tags: ant

- name: Add Ant binaries to PATH environment variable
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/opt/devops/apache-ant-{{ ant_version }}/bin).*?)(["]*)$' line="PATH=\1\2:/opt/devops/apache-ant-{{ ant_version }}/bin\3"
  tags: ant   