---

galaxy_info:
  author: Nagesh Ogiboina
  description: Ansible Role for Atlassian BitBucket Installation.
  company: Sapient Consulting pvt ltd
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - system
dependencies: []
