---
# tasks file for nagesh.bitbucket

- name: create group
  group:
    name: "{{ bitbucket_user }}"
    gid: "{{ bitbucket_gid | default(None) or omit }}"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: nagesh.bitbucket

- name: create user
  user:
    name: "{{ bitbucket_user }}"
    password: "{{ bitbucket_pass | password_hash('sha512', bitbucket_hash_salt) }}"
    home: "{{ bitbucket_home }}"
    group: "{{ bitbucket_user }}"
    uid: "{{ bitbucket_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: nagesh.bitbucket

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ bitbucket_catalina }}", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755", state: "directory" }
  notify: restart bitbucket
  tags: nagesh.bitbucket

- name: download package
  get_url:
    url: "{{ bitbucket_url }}"
    dest: "/tmp/{{ bitbucket_archive }}"
    checksum: "{{ bitbucket_checksum }}"
  tags: nagesh.bitbucket

- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ bitbucket_archive }} -C {{ bitbucket_catalina }} --strip-components=1
    chown -Rf {{ bitbucket_user }}:{{ bitbucket_user }} {{ bitbucket_catalina }}
  args:
    creates: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
  notify: restart bitbucket
  tags: nagesh.bitbucket

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/init.d/bitbucket.j2", dest: "/etc/init.d/bitbucket", owner: "root", group: "root", mode: "0755" }
    - { src: "usr/share/bitbucket/bin/setenv.sh.j2", dest: "{{ bitbucket_catalina }}/bin/setenv.sh", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0644" }
    - { src: "usr/share/bitbucket/conf/server.xml.j2", dest: "{{ bitbucket_catalina }}/conf/server.xml", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0644" }
  notify: restart bitbucket
  tags: nagesh.bitbucket

- name: enable service
  service:
    name: "bitbucket"
    enabled: "yes"
  notify: restart bitbucket
  tags: nagesh.bitbucket
